### ISSUE TITLE
if set css:false in compilerOptions i get current error

### ISSUE THREAD

**Issue by timeshift92** [AlexxNB/svelte-esbuild-starter#1] opened 2021-02-23 17:05 UTC
![image](https://user-images.githubusercontent.com/13614530/108879482-2153b900-7623-11eb-9b93-2ebcfc5ec8c3.png)

**Comment by AlexxNB** [comment] 2021-02-23 19:41
Hmm.. `css` is `false` by default and works great. Please give me more info.

**Comment by AlexxNB** [comment] 2021-02-23 19:44
Ah,ok... I just try to setup project from scratch and get this error... Will try to fix it. Thanks.

**Comment by AlexxNB** [comment] 2021-02-24 04:53
The problem with esbuild-svelte plugin. I wrote issue to its repo  https://github.com/EMH333/esbuild-svelte/issues/33

**Comment by AlexxNB** [comment] 2021-02-24 04:54
Now you can downgrade to esbuild@0.5.0 to temporally fix the problem.

**Comment by AlexxNB** [comment] 2021-02-24 20:28
The problem is fixed in `esbuild-svelte`, so just run `npm i -D esbuild-svelte` to fix your issue.

**Closed as completed by AlexxNB** 2021-02-24 20:28 UTC

**Comment by timeshift92** [comment] 2021-02-25 02:37
Cool, thanks
